import { z } from 'zod';
import type { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { refsSchema, type MCPContent } from './shared.js';
import type { Store } from '../tasks.js';
import {
  handleGetByType,
  handleGetOverview,
  handleGetNext,
  handleGetAll,
  handleGetById,
  handleGetByScope,
  handleGetRelated,
  handleGetScopes,
  handleHealth,
} from './queryHandlers.js';
import {
  handleAdd,
  handleUpdate,
  handleSetStatus,
  handleDelete,
  handleUiStart,
  handleUiStop,
} from './mutationHandlers.js';

const statusParam = z.enum(['refinement', 'todo', 'in_progress', 'done', 'open']).optional()
  .describe('Filter by status. Default: non-done. Pass "open" for refinement+todo+in_progress, or a specific status (incl. "done") for exact match.');

export function registerTools(server: McpServer, store: Store): void {
  // ── add ────────────────────────────────────────────────────────────────────────
  const addSchema = {
    type: z.enum(['bug', 'feature', 'idea', 'tool', 'other'])
      .describe('bug = defect to fix (highest priority class); feature = planned work that requires a /plan session before implementation; idea = exploratory thought, needs refinement before it becomes a feature; tool = developer-tooling improvement; other = anything that does not fit the above'),
    priority: z.enum(['low', 'medium', 'high', 'critical'])
      .describe('critical = blocking or data-loss risk, fix immediately; high = important, tackle soon; medium = normal backlog; low = nice-to-have'),
    title: z.string().min(1, 'Title must not be empty')
      .describe('Short, action-oriented title — start with a verb (e.g. "Fix undo animation glitch on session delete", "Add dark-mode toggle to settings")'),
    description: z.string().optional().default('')
      .describe('Full context the implementer will need: what is broken or needed, reproduction steps or acceptance criteria, relevant file paths, technical constraints. Be thorough — this is what the next session will read.'),
    scope: z.string().optional()
      .describe('Optional tool or area this task belongs to (e.g. "svg-path-joiner", "eink-frame", "task-manager"). Omit for project-wide tasks. Use getByScope to filter tasks by this value later.'),
    summary: z.string().optional()
      .describe('Short 2–3 line gist of the task (what it does, key decision, user-visible outcome). Generated by /refine before promotion to todo. Can be set manually here if known at creation time.'),
    plan: z.string().optional()
      .describe('Optional implementation plan in markdown. Written by the agent after /plan; read back via getById before /implement.'),
    refs: refsSchema
      .describe('Optional related-task references — use when this task depends on, blocks, or is otherwise connected to existing tasks. Each entry: { id: number, relation?: string }. Relation must be one of the canonical values; default "relates to". The server automatically writes the inverse on the referenced task — you only need to specify one side.'),
    status: z.enum(['refinement', 'todo']).default('refinement')
      .describe('Initial status. ALWAYS leave as default "refinement" unless one of these holds: (a) the user explicitly told you to skip refinement / mark as todo, or (b) you just refined this exact task with the user in the current conversation. Otherwise pass "refinement" (or omit the field). Choosing "todo" without one of those conditions is a rule violation — when in doubt, pick "refinement".'),
  };
  server.tool(
    'add',
    'Schedule a new task — call this whenever the user reports a bug, requests a feature, shares an idea, or says "schedule" / "TODO" / "add to the list". Do NOT implement the task inline; add it and stop. New tasks ALWAYS default to status "refinement"; only pass status: "todo" when (a) the user explicitly asks to skip refinement, OR (b) the current conversation already refined this exact task with the user. When in doubt, omit status and let the next session run PM-style clarification. Returns { id } of the newly created task. Refs are auto-mirrored on the other side; no need for a separate update call. Refs pointing to nonexistent IDs or self-references are silently dropped.',
    addSchema,
    async (args: z.infer<z.ZodObject<typeof addSchema>>): Promise<MCPContent> => handleAdd(store, args)
  );

  // ── getByType ──────────────────────────────────────────────────────────────────
  const getByTypeSchema = {
    type: z.enum(['bug', 'feature', 'idea', 'tool', 'other']).describe('Task type to filter: bug | feature | idea | tool | other'),
    status: statusParam,
  };
  server.tool(
    'getByType',
    'Get tasks of a specific type — use for "show me all bugs", "list features", "what ideas do we have?". Filters by status. Default: non-done. Pass "open" for refinement+todo+in_progress, or a single status (incl. "done") for exact match. Sorted by priority desc then id desc. When a task has a summary, description is omitted — call getById for the full task.',
    getByTypeSchema,
    async (args: z.infer<z.ZodObject<typeof getByTypeSchema>>): Promise<MCPContent> => handleGetByType(store, args)
  );

  // ── getOverview ────────────────────────────────────────────────────────────────
  const getOverviewSchema = { status: statusParam };
  server.tool(
    'getOverview',
    'Get a count summary per type: refinement, open (todo + in_progress), and done counts. Use for dashboard questions like "how many tasks are there?" or "give me a backlog summary". Filters by status. Default: non-done. Pass "open" for refinement+todo+in_progress, or a single status (incl. "done") for exact match. Returns only types with at least one matching task, sorted by open count desc. Do NOT use this to answer "what\'s next?" — use getNext for that.',
    getOverviewSchema,
    async (args: z.infer<z.ZodObject<typeof getOverviewSchema>>): Promise<MCPContent> => handleGetOverview(store, args)
  );

  // ── getNext ────────────────────────────────────────────────────────────────────
  const getNextSchema = {
    type: z.enum(['bug', 'feature', 'idea', 'tool', 'other']).optional()
      .describe('Narrow to one type (optional). Omit to recommend across all types using the bug > tool > feature > idea > other order.')
  };
  server.tool(
    'getNext',
    'Get the single next actionable task — use for "what should I do next?", "what\'s next?", or any recommendation request. Sort order: in_progress first (resume interrupted work), then refinement (needs PM clarification), then todo, then highest priority, then newest id (FILO). Considers refinement, todo, and in_progress tasks. Optional type filter narrows to one category. When no filter is given, apply the project prioritization order: bug > tool > feature > idea > other. IMPORTANT: if the returned task has status "refinement", do NOT start implementing — instead ask the user clarifying questions to refine the description, then promote to "todo" via setStatus. When a task has a summary, description is omitted — call getById for the full task.',
    getNextSchema,
    async (args: z.infer<z.ZodObject<typeof getNextSchema>>): Promise<MCPContent> => handleGetNext(store, args)
  );

  // ── getAll ─────────────────────────────────────────────────────────────────────
  const getAllSchema = { status: statusParam };
  server.tool(
    'getAll',
    'Get tasks grouped by type — use for "show me everything", "list all tasks", "full backlog". Groups appear in type order: bug, feature, idea, tool, other. Each group sorted by priority desc then id desc. Filters by status. Default: non-done. Pass "open" for refinement+todo+in_progress, or a single status (incl. "done") for exact match. Prefer getNext for a single recommendation; prefer getByType when the user asks about one specific type. When a task has a summary, description is omitted — call getById for the full task.',
    getAllSchema,
    async (args: z.infer<z.ZodObject<typeof getAllSchema>>): Promise<MCPContent> => handleGetAll(store, args)
  );

  // ── getById ────────────────────────────────────────────────────────────────────
  const getByIdSchema = { id: z.coerce.number().int().positive().describe('The numeric task ID to look up') };
  server.tool(
    'getById',
    'Get a single task by its numeric ID — returns the full task including both summary (if set) and description. Other list methods omit description when summary is present — use this when you need the full body. Use when the user asks about a specific task by number (e.g. "show me #42", "what is task 37?"). Returns an error listing valid IDs if not found.',
    getByIdSchema,
    async (args: z.infer<z.ZodObject<typeof getByIdSchema>>): Promise<MCPContent> => handleGetById(store, args)
  );

  // ── setStatus ──────────────────────────────────────────────────────────────────
  const setStatusSchema = {
    id: z.coerce.number().int().positive().describe('Task ID — get it from getNext, getAll, getByType, or getById'),
    status: z.enum(['refinement', 'todo', 'in_progress', 'done']).describe('refinement = needs PM clarification before work starts; todo = ready to implement; in_progress = actively being worked on (set this before beginning); done = completed and committed (set this after user confirms the commit)')
  };
  server.tool(
    'setStatus',
    'Update a task\'s status. Lifecycle rules: always call setStatus(in_progress) before starting work on a task; always call setStatus(done) after the commit is made and the user confirms. Returns { success: true } or { success: false, error }.',
    setStatusSchema,
    async (args: z.infer<z.ZodObject<typeof setStatusSchema>>): Promise<MCPContent> => handleSetStatus(store, args)
  );

  // ── update ────────────────────────────────────────────────────────────────────
  const updateSchema = {
    id: z.coerce.number().int().positive().describe('Task ID to update — get it from getNext, getAll, getById, etc.'),
    title: z.string().min(1).optional().describe('New title (replaces current). Start with a verb.'),
    description: z.string().optional().describe('New description (replaces current). Include full context: what, why, acceptance criteria, file paths.'),
    priority: z.enum(['low', 'medium', 'high', 'critical']).optional().describe('New priority: critical = blocking; high = important soon; medium = normal; low = nice-to-have'),
    type: z.enum(['bug', 'feature', 'idea', 'tool', 'other']).optional().describe('New type — use to reclassify a task (e.g. idea → feature after refinement)'),
    scope: z.string().nullable().optional().describe('New scope tag (e.g. "eink-frame"), or null to clear the scope entirely'),
    summary: z.string().nullable().optional()
      .describe('Short 2–3 line summary of the task. Pass null or empty string to clear it. Should capture: what the task does, the most important decision, and the user-visible outcome.'),
    plan: z.string().nullable().optional()
      .describe('New plan content (markdown). Pass null or empty string to clear.'),
    refs: refsSchema.nullable()
      .describe('Full replacement list of related-task references, or null / empty array to clear all refs. Each entry: { id, relation? } where relation is one of the canonical values. Defaults to "relates to". The server automatically updates the inverse on each referenced task — only specify one side. This replaces the existing refs list entirely — include all refs you want to keep.'),
  };
  server.tool(
    'update',
    'Patch any fields of an existing task in place — use when the user asks to edit, rename, reprioritize, retype, rescope, or update the refs/description of a task. Only the fields you provide are changed; omitted fields keep their current values. Returns { success: true, task } with the full updated task, or { success: false, error }. Refs pointing to nonexistent IDs or self-references are silently dropped.',
    updateSchema,
    async (args: z.infer<z.ZodObject<typeof updateSchema>>): Promise<MCPContent> => handleUpdate(store, args)
  );

  // ── getByScope ────────────────────────────────────────────────────────────────
  const getByScopeSchema = {
    scope: z.string().describe('Exact scope value to filter by (e.g. "svg-path-joiner"). Must match exactly — scope is case-sensitive.'),
    status: statusParam,
  };
  server.tool(
    'getByScope',
    'Get tasks tagged with a specific scope — use when the user asks "what tasks are there for svg-path-joiner?" or "show me everything related to eink-frame". Filters by status. Default: non-done. Pass "open" for refinement+todo+in_progress, or a single status (incl. "done") for exact match. Sorted by priority desc then id desc. Scope values are set via add or update. Empty results may indicate a wrong/typo\'d scope; use getScopes to discover valid values. When a task has a summary, description is omitted — call getById for the full task.',
    getByScopeSchema,
    async (args: z.infer<z.ZodObject<typeof getByScopeSchema>>): Promise<MCPContent> => handleGetByScope(store, args)
  );

  // ── getRelated ────────────────────────────────────────────────────────────────
  const getRelatedSchema = {
    id: z.coerce.number().int().positive().describe('Task ID to find related tasks for'),
    status: statusParam,
  };
  server.tool(
    'getRelated',
    'Get tasks related to a given task — returns the task itself, outbound (tasks that #X references, decorated with refRelation), and inbound (tasks that reference #X). Filters by status. Default: non-done. Pass "open" for refinement+todo+in_progress, or a single status (incl. "done") for exact match. The anchor task is full view (summary + description); outbound and inbound entries follow list mode (summary when present, description otherwise).',
    getRelatedSchema,
    async (args: z.infer<z.ZodObject<typeof getRelatedSchema>>): Promise<MCPContent> => handleGetRelated(store, args)
  );

  // ── getScopes ─────────────────────────────────────────────────────────────────
  server.tool(
    'getScopes',
    'List all scopes that exist across active and done tasks — use to discover valid scope values before calling getByScope or getByStatus with a scope filter. Returns { scopes: Array<{ scope, total, open }> }. Sorted: open desc, then total desc, then alphabetically.',
    {},
    async (): Promise<MCPContent> => handleGetScopes(store)
  );

  // ── health ────────────────────────────────────────────────────────────────────
  server.tool(
    'health',
    'Validate the task-manager setup AND report the UI URL. Checks .mcp.json config, probes the UI port, verifies DB migrations, and confirms /refine + /implement skills are installed. Returns a human-readable health report with ✓/⚠/✗ status lines, actionable fix instructions, and the localhost + LAN-IP URLs for the task-manager UI. Call this when the user asks where the UI is, asks for the link, or wants the URL to open the task-manager in their browser — the LAN URL in the Runtime section is the clickable address.',
    {},
    async (): Promise<MCPContent> => handleHealth()
  );

  // ── delete ────────────────────────────────────────────────────────────────────
  const deleteSchema = { id: z.coerce.number().int().positive().describe('The numeric task ID to permanently remove') };
  server.tool(
    'delete',
    'Permanently remove a task from the database. Use ONLY when the user explicitly asks to delete, remove, drop, or cancel a task — not when work is finished (use setStatus(done) for that). Cascade-removes refs from/to this task. This is irreversible.',
    deleteSchema,
    async (args: z.infer<z.ZodObject<typeof deleteSchema>>): Promise<MCPContent> => handleDelete(store, args)
  );

  // ── ui-start ──────────────────────────────────────────────────────────────────
  server.tool(
    'ui-start',
    'Start the task-manager-ui if not already running. Idempotent — returns alreadyRunning if the port is already in use. Respects TASK_UI_DISABLE.',
    {},
    async (): Promise<MCPContent> => handleUiStart()
  );

  // ── ui-stop ───────────────────────────────────────────────────────────────────
  server.tool(
    'ui-stop',
    'Stop the task-manager-ui if running and owned by this MCP process. No-op if already down. Returns a warning if the UI is running but was started externally.',
    {},
    async (): Promise<MCPContent> => handleUiStop()
  );
}
