#!/usr/bin/env node
/**
 * setup-standalone.ts on|off — per-project toggle for pm2-managed standalone UI mode.
 *
 * Run from the project root (the directory containing `.mcp.json`):
 *
 *   npx tsx ~/.claude/mcp-servers/simple-task-manager/setup-standalone.ts on
 *   npx tsx ~/.claude/mcp-servers/simple-task-manager/setup-standalone.ts off
 *
 * `on`  — sets TASK_UI_MODE=standalone in .mcp.json, ensures PROJECT_NAME / TASK_UI_PORT,
 *         writes <project>/ecosystem.task-ui.config.cjs, runs `pm2 start && pm2 save`.
 * `off` — runs `pm2 delete <PROJECT_NAME>`, sets TASK_UI_MODE=bundled, removes the
 *         generated ecosystem file.
 *
 * After either command, restart Claude Code so the MCP picks up the new env block.
 *
 * The script reads/writes .mcp.json via the shared JSONC helper so the user-facing
 * comments install.ts emits are preserved across edits.
 */
import { readFileSync, writeFileSync, existsSync, unlinkSync } from 'node:fs';
import { resolve, basename, dirname } from 'node:path';
import { execSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { parseMcpConfig, serializeMcpConfig } from './mcpConfig.js';

const HERE = dirname(fileURLToPath(import.meta.url));
const UI_CWD = resolve(HERE, 'task-manager-ui');

const mode = process.argv[2];
if (mode !== 'on' && mode !== 'off') {
  console.error('Usage: setup-standalone.ts on|off  (run from the project directory)');
  process.exit(1);
}

const projectDir = process.cwd();
const mcpFile = resolve(projectDir, '.mcp.json');
const ecosystemFile = resolve(projectDir, 'ecosystem.task-ui.config.cjs');

if (!existsSync(mcpFile)) {
  console.error(`No .mcp.json in ${projectDir}. Run install.ts first to register the task-manager MCP.`);
  process.exit(1);
}

const config = (() => {
  try {
    return parseMcpConfig(readFileSync(mcpFile, 'utf8'));
  } catch (err) {
    console.error(`Failed to parse ${mcpFile}: ${(err as Error).message}`);
    process.exit(1);
  }
})();

const tmEntry = config.mcpServers?.['task-manager'];
if (!tmEntry) {
  console.error(`No "task-manager" entry in ${mcpFile}. Run install.ts first.`);
  process.exit(1);
}
tmEntry.env ??= {};
const env = tmEntry.env;

function writeMcp(): void {
  writeFileSync(mcpFile, serializeMcpConfig(config));
}

function pm2(cmd: string, { ignoreFailure = false }: { ignoreFailure?: boolean } = {}): void {
  try {
    execSync(cmd, { stdio: 'inherit' });
  } catch (err) {
    if (!ignoreFailure) throw err;
  }
}

if (mode === 'on') {
  // Ensure standard params, then flip TASK_UI_MODE.
  const projectName = env['PROJECT_NAME'] || basename(projectDir);
  const port = env['TASK_UI_PORT'] || '7374';
  const tasksDb = env['TASKS_DB'] || resolve(projectDir, 'tasks.db');
  env['PROJECT_NAME'] = projectName;
  env['TASK_UI_PORT'] = port;
  env['TASKS_DB'] = tasksDb;
  env['TASK_UI_MODE'] = 'standalone';
  writeMcp();

  // Generate ecosystem file. Filename MUST include `.config.` — pm2 only treats
  // a file as an ecosystem config when its name matches that pattern; otherwise
  // it parses the file as a script and ignores apps[].name (process ends up
  // named after the file rather than PROJECT_NAME).
  const ecosystem = `// Generated by setup-standalone.ts — edit .mcp.json + re-run setup-standalone.ts to regenerate.
module.exports = {
  apps: [{
    name: ${JSON.stringify(projectName)},
    script: 'server.ts',
    interpreter: 'node',
    interpreter_args: '--import tsx',
    cwd: ${JSON.stringify(UI_CWD)},
    env: {
      TASKS_DB: ${JSON.stringify(tasksDb)},
      PROJECT_NAME: ${JSON.stringify(projectName)},
      TASK_UI_PORT: ${JSON.stringify(port)},
      // Tells the UI server it's running standalone so /api/config reports
      // "standalone" to the browser and the header label is correct.
      TASK_UI_MODE: 'standalone',
    },
  }],
};
`;
  writeFileSync(ecosystemFile, ecosystem);

  // Replace any previous registration with the same name, then start fresh.
  pm2(`pm2 delete ${JSON.stringify(projectName)}`, { ignoreFailure: true });
  pm2(`pm2 start ${JSON.stringify(ecosystemFile)}`);
  pm2('pm2 save');

  console.log(`\nStandalone UI started as "${projectName}" on port ${port}.`);
  console.log(`Restart Claude Code to pick up the .mcp.json change.`);
  process.exit(0);
}

// mode === 'off'
const projectName = env['PROJECT_NAME'];
if (projectName) {
  pm2(`pm2 delete ${JSON.stringify(projectName)}`, { ignoreFailure: true });
  pm2('pm2 save', { ignoreFailure: true });
} else {
  console.warn(`PROJECT_NAME not set in ${mcpFile} — skipping pm2 delete. If a standalone process is still running, stop it manually.`);
}

env['TASK_UI_MODE'] = 'bundled';
writeMcp();

if (existsSync(ecosystemFile)) {
  unlinkSync(ecosystemFile);
}

console.log(`\nStandalone UI removed. Restart Claude Code so the MCP resumes spawning the UI.`);
